language: node_js
sudo: false
node_js:
  - "8"
  - "7"
  - "6"
  - "4"
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: yarn test
after_script: greenkeeper-lockfile-upload
after_success: bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
