language: node_js
sudo: false
node_js:
  - "9"
  - "8"
before_install: yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - 'if [[ -n "$TRAVIS_TAG" ]] && [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then yarn run create-github-release; fi'
script:
  - yarn lint
  - yarn flow
  - yarn test:coverage
after_script: greenkeeper-lockfile-upload
after_success: bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
